# Generated by Django 4.1 on 2022-09-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_post'),
        ('blog', '0004_alter_post_id'),
    ]

    operations = [
    ]
